### ISSUE TITLE
ErrorException in Date.php line 6: Declaration of Jenssegers\Date\Date::setTranslator() should be compatible with Carbon\Carbon::setTranslator

### ISSUE THREAD

**Issue by cschalenborgh** [jenssegers/laravel-date#112] opened 2015-03-26 10:19 UTC
Hi Jens,

I got this error on my Laravel 5 install after updating your library through composer. Any ideas?
```
ErrorException in Date.php line 6: Declaration of Jenssegers\Date\Date::setTranslator() should be compatible with Carbon\Carbon::setTranslator(Symfony\Component\Translation\TranslatorInterface $translator)
```

**Comment by jenssegers** [comment] 2015-03-26 10:21
Duplicate of #108, it should already be fixed on master.

**Comment by bobbybouwmann** [comment] 2015-03-26 10:35
It's still not working on my end! Tried dev-master as well, but that didn't do anything as well!

My laravel 5 installation pulls in Carbon 1.18.0

The error message: 
```
Declaration of Jenssegers\Date\Date::setTranslator() should be compatible with Carbon\Carbon::setTranslator(Symfony\Component\Translation\TranslatorInterface $translator)
```

**Comment by jenssegers** [comment] 2015-03-26 10:39
See: https://github.com/jenssegers/laravel-date/blob/master/src/Date.php#L381

**Comment by bobbybouwmann** [comment] 2015-03-26 10:43
So I opened that class on my installation and I get this
```
/**
     * Set the Translator implementation
     *
     * @param Translator  $translator
     */
    public static function setTranslator($translator)
    {
        static::$translator = $translator;
    }
```

Did you update the package so it's available through composer?

**Comment by jenssegers** [comment] 2015-03-26 22:46
I created a 2.0 branch and tagged version 2.0.21 that locks down the Carbon version to <1.18. This should fix it until v3 is released.

**Comment by bobbybouwmann** [comment] 2015-03-28 07:29
Thanks you :D

**Closed** 2015-04-11 09:09 UTC

**Comment by LoveAndHappiness** [comment] 2015-04-15 11:05
So what exactly is the fix for this now?

**Comment by Piusyo** [comment] 2018-03-01 08:18
The issue is still there, why is it closed?

**Comment by danhunsaker** [comment] 2018-03-01 09:26
Because the current issue is a different one that only looks similar.

**Comment by Piusyo** [comment] 2018-03-01 09:30
Declaration of Jenssegers\Date\Date::diffForHumans() should be compatible with Carbon\Carbon::diffForHumans(Carbon\
Carbon $other = NULL, $absolute = false, $short = false, $parts = 1)

**Comment by danhunsaker** [comment] 2018-03-01 09:36
Yes. Look at #280 for the current issue. This one was about a completely different method.
